#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "protonmail-bridge"
name = "ProtonMail Bridge"
description.en = "Use Proton Mail with your email client"
description.fr = "Utilisez Proton Mail avec votre client de messagerie"

version = "3.12.0~ynh1"

maintainers = ["CodeShakingSheep"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://proton.me/mail/bridge"
admindoc = "https://proton.me/support/protonmail-bridge-install"
userdoc = "https://proton.me/support/protonmail-bridge-install"
code = "https://github.com/ProtonMail/proton-bridge"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = ["amd64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.admin]
    type = "user"

    [install.user]
    type = "string"
    ask.en = "Enter your Protonmail account user"
    ask.fr = "Entrez l'utilisateur de votre compte ProtonMail"

    [install.password]
    help.en = "Enter your Protonmail account password"
    help.fr = "Entrez le mot de passe du compte ProtonMail"
    type = "password"

    [install.twofa]
    ask.en = "If you have 2FA enabled for your account, enter the current code"
    ask.fr = "Si 2FA a activé pour votre compte, entrez le code actuel"
    type = "password"
    default = ""

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/ProtonMail/proton-bridge/archive/refs/tags/v3.12.0.tar.gz"
        sha256 = "4215fd1848fff262da55194270f495e19722cdf8bbf98dbe3ca4ff5ca5aa4a1f"
        format = "tar.gz"
        in_subdir = true
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.apt]
    packages = "gpg, libsecret-1-dev, pass, zip, cmake, build-essential, ninja"
