#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "protonmail-bridge"
name = "ProtonMail Bridge"
description.en = "Use Proton Mail with your email client"
description.fr = "Utilisez Proton Mail avec votre client de messagerie"

version = "3.4.2~ynh1"

maintainers = ["CodeShakingSheep"]

[upstream]
license = "GNU 3.0"
website = "https://proton.me/mail/bridge"
admindoc = "https://proton.me/support/protonmail-bridge-install"
userdoc = "https://proton.me/support/protonmail-bridge-install"
code = "https://github.com/ProtonMail/proton-bridge"

[integration]
yunohost = ">= 11.1.21"
architectures = "amd64"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.admin]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # Note that user-provided passwords questions are not automatically saved as setting
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/ProtonMail/proton-bridge/archive/refs/tags/v3.4.2.tar.gz"
        sha256 = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.apt]
    packages = "gpg, pass"
