#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

user=$YNH_APP_ARG_USER
ynh_app_setting_set --app=$app --key=user --value="$user"
password=$YNH_APP_ARG_PASSWORD
ynh_app_setting_set --app=$app --key=password --value="$password"
twofa=$YNH_APP_ARG_TWOFA
ynh_app_setting_set --app=$app --key=twofa --value="$wofa"

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/build"

chown -R $app:www-data "$install_dir"

#=================================================
# SPECIFIC SETUP
#=================================================
# BUILD APP
#=================================================
ynh_script_progression --message="Building app..." --weight=1

ynh_exec_warn_less ynh_install_go --go_version=$go_version
ynh_use_go

ynh_exec_warn_less ynh_exec_as $app make build-nogui

ynh_remove_go

#=================================================
# LOGIN USER TO BRIDGE
#=================================================
ynh_script_progression --message="Loggin in user to $app... (depending on the amount of mails this can take seconds or several minutes)" --weight=1
ynh_exec_warn_less ynh_exec_as $app echo -e "login"\n"$user"\n"$password"\n"$twofa" | ./bridge --cli & PID=$
wait $PID

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated systemd config
ynh_add_systemd_config

yunohost service add $app --description="Use Proton Mail with your email client" --log="/var/log/$app/$app.log"


#=================================================
# GENERIC FINALIZATION
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
