#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..." --weight=1

ynh_restore_file --origin_path="$install_dir"

chown -R $app:www-data "$install_dir"

#=================================================
# LOGIN USER TO BRIDGE
#=================================================
ynh_script_progression --message="Loggin in user to $app... (depending on the amount of mails this can take seconds or several minutes)" --weight=1
ynh_exec_warn_less ynh_exec_as $app echo -e "login"\n"$user"\n"$password"\n"$twofa" | ./bridge --cli & PID=$
wait $PID

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
# RESTORE SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

yunohost service add $app --description="Use Proton Mail with your email client" --log="/var/log/$app/$app.log"

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression --message="Reloading $app's service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
