#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir/build"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

ynh_go_install

pushd $install_dir/build
    ynh_hide_warnings make build-nogui
popd

ynh_go_remove

#=================================================
# LOGIN USER TO BRIDGE
#=================================================
ynh_script_progression "Loggin in user to $app... (depending on the amount of mails this can take seconds or several minutes)"

ynh_hide_warnings ynh_exec_as_app echo -e "login"\n"$user"\n"$password"\n"$twofa" | ./bridge --cli & PID=$
wait $PID

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_systemd

yunohost service add $app --description="Use Proton Mail with your email client" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
